language: node_js
script: make test
node_js:
- '0.10'
- '0.11'
services:
- mongodb
env:
  global:
    - secure: Vw+Swj8Qef7GXHC8jyxCLgGZu9vL/Xm1q5AVCoT7kafT+eIXBTXo2lEhpzYQKX7Udhy4aKDaEHNPOkE++aFSMEkmjmauty6R7xf7/JRxvCfVnztciGTHgyihyRWj+YwPTjyua61TePe63G1Hr6rsDvxfOqC/AFVa4oSjvRuDTPA=
