language: node_js
script: make test
node_js:
- '0.10'
- '0.11'
services:
- mongodb
env:
  global:
  - secure: k05bP5RU2E9+8g3L0ZfuN4Tx1ZsDr/4UhMwG3Gn7fblyyTetX+bvxZ2vusmlgECJtORbibnPG81PbxZUoJF8tk+qQlOoCPZg1kCwn2Eam8rnLNKu5ZS0sbxEBBeyB44v/P9nNB86P2zWJuqkCcUDOOdbq5QXQ2zEz/q/NHqdcuM=
